# Generated by Django 4.1.6 on 2023-02-11 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Proposed'), ('2', 'Approved'), ('3', 'Denied')], default='1', max_length=1)),
                ('item_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_primary', to='main_app.item')),
                ('item_proposed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_proposed', to='main_app.item')),
            ],
        ),
    ]
