# Generated by Django 4.1.6 on 2023-02-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Ready to Trade'), ('3', 'Traded')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='trade',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
