# Generated by Django 4.1.6 on 2023-02-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Sporting Goods', 'Sporting Goods'), ('Jewelry', 'Jewelry'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='Clothing', max_length=15),
        ),
    ]
