# Generated by Django 4.1.6 on 2023-02-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='item_comment',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, related_name='item_comment', to='main_app.item'),
        ),
    ]
